
version: '3.5'

services:
  db_auth:
    container_name: ${APP_DB_NAME}
    image: postgres:13.11-bullseye
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - ${APP_DB_PORT}:5432

volumes:
  postgres-db:
    driver: local